### ISSUE TITLE
No information about user account authentication in webhooks.

### ISSUE THREAD

**Issue by syrsly** [BotEngineAI/php-webhook-example#3]
Is there some way to send a user's username to Chatbot to be used for webhooks? I noticed the default_username value in the object, but it's always null and no examples given of website integration of user data.

**Comment by aPoCoMiLogin** [comment]
Hi there, some attributes aren't always filled, the `default_username` is used by slack integration, in other integrations is empty.

The `default_name` attribute is what's used as the name of the user. Here's a matrix table: https://www.chatbot.com/help/attributes/attributes-and-integrations/

**Comment by aPoCoMiLogin** [comment]
Also if you want to set some attributes, just return from you webhook JSON object like this:

```json
{
  "parameters": {
    "default_name": "John Doe"
  }
}
```
